stages:
 - build

build-latest:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - 'docker login -u nilsramsperger -p $DOCKERHUB_TOKEN'
    - 'docker build --no-cache -t nilsramsperger/nodebb:latest .'
    - 'docker push nilsramsperger/nodebb:latest'
  only:
    - master

build-tags:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - 'docker login -u nilsramsperger -p $DOCKERHUB_TOKEN'
    - 'docker build --no-cache -t nilsramsperger/nodebb:$CI_BUILD_REF_NAME .'
    - 'docker push nilsramsperger/nodebb:$CI_BUILD_REF_NAME'
  only:
    refs:
      - tags

