stages:
  - build

build:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - "docker login -u nilsramsperger -p $DOCKERHUB_TOKEN"
    - "docker build --no-cache -t nilsramsperger/nodebb:latest ."
  only:
    refs:
      - master
    changes:
      - Dockerfile
      - .gitlab-ci.yml
      - files/**/*

publish:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - "docker login -u nilsramsperger -p $DOCKERHUB_TOKEN"
    - "docker build --no-cache -t nilsramsperger/nodebb:$CI_BUILD_REF_NAME ."
    - "docker push nilsramsperger/nodebb:$CI_BUILD_REF_NAME"
    - "docker tag nilsramsperger/nodebb:$CI_BUILD_REF_NAME nilsramsperger/nodebb:latest"
    - "docker push nilsramsperger/nodebb:latest"
  only:
    refs:
      - tags
