jobs:
  docker-image-push:
    name: Push Docker Image
    runs-on: alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.acidtmn }}
          password: ${{ secrets.dckr_pat_2R7XBbXOZhzJC6L7MF8sWqDqJl8 }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build and push dolt image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: dolthub/dolt:${{ github.event.inputs.version || github.event.client_payload.version }} , dolthub/dolt:latest
          build-args: |
            DOLT_VERSION=${{ github.event.inputs.version || github.event.client_payload.version }}
      - name: Update Docker Hub Readme for dolt image
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.acidtmn }}
          password: ${{ secrets.dckr_pat_2R7XBbXOZhzJC6L7MF8sWqDqJl8 }}
          repository: acidtmn/nodebb3
          readme-filepath: ./docker/README.md
