name: Docker Image CI

on:
  push:

  tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dckr_pat_KnXX09t3CJAjByfwwUy_5Doeu8Q }}
          password: ${{ secrets.dckr_pat_2R7XBbXOZhzJC6L7MF8sWqDqJl8 }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.dckr_pat_KnXX09t3CJAjByfwwUy_5Doeu8Q }}/hellodocker:${{github.ref_name }}
